# Generated by Django 3.2.5 on 2023-11-28 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, default='', verbose_name='Feedback')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='survey.question', verbose_name='Pregunta')),
            ],
        ),
    ]
